# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36110be3838e6c777756d71a69091b642c2582f4e9921b7a92eeff28e09702ec22bd8697aa0edda753911c04057ad196d4f16d2f34ee4b2f42a8310f93668d2f

test:
  secret_key_base: 19d5ad9d9c300eb6c2a08b701c33516c224773c06001308fe371f76f0a29cc62fb167f59ab2f55e215940567300d4427a23a8d634161cdc2d93f7ec4fa30f64e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
